### ISSUE TITLE
Symbol.asyncIterator is not defined.

### ISSUE THREAD

**Issue by kedar9444** [jamiemccrindle/axax#24]
Symbol.asyncIterator is not defined. 
The issue occurs due to old version of node. 
Then i tried to update the global version of node but no joy.
Once i updated the local version of  node the issue got fixed which added  the node dependency in project.
Whats is your view on this?

#AMotivatedContributor

**Comment by jamiemccrindle** [comment]
Feel free to commit and I’ll fix the nodejs dependency

**Comment by kedar9444** [comment]
@jamiemccrindle  : BTW how can i debug these test cases ?

**Comment by Naycon** [comment]
@kedar9444, if you run VSCode and the jest plugin, you can click a debug button over a test in the editor itself to debug a test. Just make a change to the test file and save it and they will appear. It's very convenient and works great. I've only tested it with the latest version of node though. Had the same problem as you but I upgraded node version instead.

**Comment by jamiemccrindle** [comment]
Thanks @Naycon!

**Comment by kedar9444** [comment]
@Naycon : can you paste here configuration in following files on your system.
jest.config.js
lauch.js

getting this 'TypeError: Symbol.asyncIterator is not defined.' this error while following your steps.
(Runs ok in git bash.)

**Comment by Naycon** [comment]
I got no special config, just the plugin to VSCode. I got the same error as you, both in bash and vscode, but it disappeared in both places after upgrading my node version from 8.something to the latest stable version.

**Comment by kedar9444** [comment]
@Naycon : okkk, let me figure it out.

**Comment by jamiemccrindle** [comment]
I closed this for now but let me know if you want it reopened. I've removed the dependency on nodejs in the package.json as it might do strange things to people's systems if they use it as a library. If it's the only way that you can work on the project, consider having a version of package.json that you don't check in.
