### ISSUE TITLE
skipWhile

### ISSUE THREAD

**Issue by jamiemccrindle** [jamiemccrindle/axax#27]
Write a skipWhile method for axax that behaves similarly to

https://www.learnrxjs.io/operators/filtering/skipwhile.html

Please check how the other methods are written in axax e.g. they typically are curried e.g. here's map:

```javascript
/**
 * Runs a mapping function over an asynchronous iterable
 */
export function map<TFrom, TTo>(
  mapper: (t: TFrom, index: number) => Promise<TTo> | TTo
) {
  return async function* inner(source: AsyncIterable<TFrom>) {
    let index = 0;
    for await (const item of source) {
      yield await mapper(item, index++);
    }
  };
}
```

**Comment by kedar9444** [comment]
@Naycon : your code helped me here, thanks.
