### ISSUE TITLE
Benefits? 

### ISSUE THREAD

**Issue by DarrylD** [jamiemccrindle/axax#4]
Wondering if it's any benefits to use this over the other libs your mentioned (lodash, underscore, Ramda or Rxjs).

Trying to make a case for it.

**Comment by jamiemccrindle** [comment]
Which library is right will depend a lot on what your needs are. 

If you're working with regular objects or arrays then lodash, underscore or Ramda would be the right choice.

If you're working with asynchronous streams of data, either axax or Rxjs could be a good choice. Subjectively (and I'm biased), I think that asynchronous iterators (with axax) can make some code easier to read / reason about. On the other hand, if you're CPU bound, I'd recommend Rx as asynchronous iterators aren't quite as fast yet.
