### ISSUE TITLE
Upgrade the dependencies to their latest versions

### ISSUE THREAD

**Issue by jamiemccrindle** [jamiemccrindle/axax#40]
The axax dependencies are slightly out of date. Update them to their latest versions (e.g. using `ncu -a` from npm-check-update.

Double check that the tests still pass once you've upgraded the versions.

```bash
ncu -a
yarn install
yarn test
```

Check out the [contributing guide](https://github.com/jamiemccrindle/axax/blob/master/CONTRIBUTING.md) to get started.

**Comment by kreatemore** [comment]
👋 	I'd be glad to do this tonight, mind if I take it?

**Comment by jamiemccrindle** [comment]
Go for it

**Comment by himankpathak** [comment]
@jamiemccrindle I was looking up this issue, I found that tests are failing when running `yarn test` without even me updating the packages.

**Comment by jamiemccrindle** [comment]
@himankpathak what version of node are you using? Unfortunately this issue is now addressed but feel free to try the others!

**Comment by himankpathak** [comment]
@jamiemccrindle I am using node version v8.12.0

**Comment by jamiemccrindle** [comment]
Async iterators require nodejs 10+ unfortunately as they are relatively new

**Comment by himankpathak** [comment]
okay, thanks for the info! :smile:
