### ISSUE TITLE
some

### ISSUE THREAD

**Issue by jamiemccrindle** [jamiemccrindle/axax#44]
Write a `some` method for axax that behaves similarly to

https://lodash.com/docs/4.17.10#some

i.e. it returns true if the predicate is true for any of the items in the source async iterator

Check out the [contributing guide](https://github.com/jamiemccrindle/axax/blob/master/CONTRIBUTING.md) to help you get started.

Please check how the other methods are written in axax e.g. they typically are curried e.g. here's map:

```javascript
/**
 * Runs a mapping function over an asynchronous iterable
 */
export function map<TFrom, TTo>(
  mapper: (t: TFrom, index: number) => Promise<TTo> | TTo
) {
  return async function* inner(source: AsyncIterable<TFrom>) {
    let index = 0;
    for await (const item of source) {
      yield await mapper(item, index++);
    }
  };
}
```

**Comment by Ricool06** [comment]
Hey @jamiemccrindle I'll jump on this. Sounds fun. :+1:

**Comment by jamiemccrindle** [comment]
Awesome. Have a look at how `every` is implemented for more clues

**Comment by Ricool06** [comment]
Are you looking for 'matches iteratee', 'matchesProperty iteratee', and 'property iteratee' shorthand too?

**Comment by Ricool06** [comment]
#45
