### ISSUE TITLE
Document fromNodeStream

### ISSUE THREAD

**Issue by jamiemccrindle** [jamiemccrindle/axax#48]
Document the [fromNodeStream](https://github.com/jamiemccrindle/axax/blob/master/src/fromNodeStream.ts) function in the [API Guide](https://github.com/jamiemccrindle/axax/blob/master/docs/API.md)

**Comment by dcarrot2** [comment]
I'll take this one on!

**Comment by jamiemccrindle** [comment]
Thanks @dcarrot2
