### ISSUE TITLE
Write tests for zip

### ISSUE THREAD

**Issue by jamiemccrindle** [jamiemccrindle/axax#49]
Write `jest` tests for the `zip` function. 

Check out the [contributing guide](https://github.com/jamiemccrindle/axax/blob/master/CONTRIBUTING.md) to help you get started.

Please have a look at how the other methods are written in axax in the `src\__tests__` directory e.g. here's the test for `first`

```javascript
import { first } from "../first";
import { of } from "../of";
import { toArray } from "../toArray";

test("first", async () => {
  const result = await toArray(first()(of(1, 2, 3, 4, 5, 6)));
  expect(result).toEqual([1]);
});

test("first with predicate", async () => {
  const result = await toArray(
      first((value: number) => value % 5 === 0)(of(1, 2, 3, 4, 5, 6)));
  expect(result).toEqual([5]);
});
```

**Comment by jamOne-** [comment]
Hey!
I would like to take this one :)

**Comment by jamiemccrindle** [comment]
Hi,

I think you've found a bug! I think line 16 should be:

```javascript
yield [firstNext.value, secondNext.value];
```

Feel free to make that change.

**Comment by jamiemccrindle** [comment]
And yeah, AsyncIterableIterator<[T, T]> would be a better return type

**Comment by jamOne-** [comment]
Oh, so I thought correctly.
Going to fix this then 😄

**Comment by jamiemccrindle** [comment]
Thanks @jamOne- for the tests, the bug fix and the better types!
