### ISSUE TITLE
Different packages

### ISSUE THREAD

**Issue by abnerey** [jamiemccrindle/axax#5]
Hello Jamie, thanks for your awesome library.
I think that axax would be better if you publish two different packages, one for es5 and another for esnext. Something like: @axax/es5 and @axax/esnext.

It's just and idea, let me know what do you thing about it.

I have some libraries too, I would be grateful if you see it and give me your feedback

**Comment by jamiemccrindle** [comment]
Thanks! I have been wondering how to manage the split between the es5 and esnext code bases. I haven't seen a consistent pattern in the wild but it does look like bundling the two together is not unusual http://2ality.com/2017/04/setting-up-multi-platform-packages.html

Tree shaking should be able to keep file sizes small.

Your libraries look great. Good luck with them!
