### ISSUE TITLE
Add argument documentation?

### ISSUE THREAD

**Issue by benjamingr** [jamiemccrindle/axax#57]
**Describe the bug**
The API docs do not contain call signatures for the functions

**To Reproduce**

Functions such as `count` or `concat` do not explain what parameters and of what type they take and return 

**Expected behavior**
Parameters should be contained in call signatures

**Environment:**
 - NodeJS version: [e.g. NodeJS 10.x]

**Additional context**

This can be done manually or generated from the TypeScript source?

**Comment by jamiemccrindle** [comment]
Done! Thanks for the suggestion @benjamingr. Let me know if the updated docs work for you.
