### ISSUE TITLE
combineLatest

### ISSUE THREAD

**Issue by benjamingr** [jamiemccrindle/axax#58]
Hey, is there a combineLatest operator like Rx's here? (If there isn't I can make a PR)

I'm trying to use axax and needed it :)

(sorry for lack of issue template, I preferred conciseness)

**Comment by jamiemccrindle** [comment]
Go for it!

**Comment by benjamingr** [comment]
New computer has no git - first draft:

```js
function combineLatest(...iterators) {
  const subject = new Subject(); // figure this out
  const nothing = Symbol();
  const filled = 0;
  let result = Array(iterators.length).fill(nothing);
  const subscriptions = iterators.map(async (iterator, i) => {
    for await(const item of iterator) {
      if (result[i] === nothing) {
        filled++;
      }
      result[i] = item;
      if (filled === iterators.length) subject.onNext(result.slice());
    }
  });
  return subject.iterator;
}
```

**Comment by jamiemccrindle** [comment]
Out at an off-site today and tomorrow but will try it out as soon as I can

**Comment by jamiemccrindle** [comment]
Dang, this is slightly harder than it looks:

* It probably needs to be filled >= iterators.length or it'll only output once
* I think in this implementation if the first iterator returns 3 values before the other iterators return values, the value of result[i] will be the last of the 3 items
* It needs a way to bail out if one of the source iterators stops (I assume?)

It may need a similar treatment to `merge` i.e. turning the iterators into callbacks and emitting events:

* when the result array is filled (for the first time)
* after that when a new value appears

Will ponder

**Comment by benjamingr** [comment]
Thanks for thee response: 

Rx behavior for comparison: https://rxviz.com/v/EOe2wy6J

I think it's fine to just drop all the values before either iterators have any values available. This is also what Rx does.

Note that `filled` is only updated when replacing a special `nothing` value - so it never gets beyond `> .length`

> It needs a way to bail out if one of the source iterators stops (I assume?)

That's true, we should probably call onCompleted and `.return` on all the iterators in a `finally` block on that `for...await`. I saved `subscriptions` on the side for that but forgot to do it.

**Comment by jamiemccrindle** [comment]
Thanks! Didn't know that `combineLatest` drops items, the visualisation is great.

I like that the `iterators.map` effectively creates `fibers`. I could probably rewrite `merge` to do the same thing.

I think it might be good to add a callback for `subject.finally` to try and close any of the source iterators if the subject's iterator gets shut down.

**Comment by jamiemccrindle** [comment]
Done!
