### ISSUE TITLE
fromNodeStream should be typed <any> for object mode

### ISSUE THREAD

**Issue by jlai** [jamiemccrindle/axax#60]
Streams can be in string/buffer mode or object mode. In the latter mode, the data emitted from the stream could be `any` (except null), but currently fromNodeStream defines its iterator result type as `<Buffer | string>`.

For people who want to consume streams in object mode, and for correctness, since you don't know if the stream being passed in is in object mode or not, it should always use `<any>`.

**Comment by jamiemccrindle** [comment]
Thanks! I'll look into it

**Comment by jamiemccrindle** [comment]
Fixed, I think.
