### ISSUE TITLE
filter doesn't handle async predicates

### ISSUE THREAD

**Issue by aaronyo** [jamiemccrindle/axax#61]
**Describe the bug**
filter(predicate) will evaluate any *async* predicate as true, because the implementation of filter does not "await" on the result of the predicate.

**To Reproduce**
```
console.log(
  await ax.toArray(ax.filter(async () => false)(ax.of(1, 2, 3)))
)
```

**Expected behavior**
Should print an empty array. Instead, prints "[1, 2, 3]".

**Environment:**
Node 10.22.0

**Comment by jamiemccrindle** [comment]
Fixed! Thanks for reporting the issue.
